### PR TITLE
fix current user middleware and npm issues

### PR DESCRIPTION
**Pull request by agonbina**
So I spent close to an hour trying to get the current user middleware to work, and it seems like the code was not even tested locally to see if it is working or not :-1: 

This pr fixes two issues:
1. Module not being exported correctly, if you install through `npm` the `main` property in package.json is set to `dist/index.js` but the gulp build will output to a folder by the name `lib`, so that should be used instead.
2. The configuration was not being passed correctly to the middleware, as well as next was not being called to move through the middleware stack.

Best,
Agon

### CODE REVIEW

**Comment by unity** [comment]
Really sorry you encountered those issues. This version isn't ready to be released and shouldn't have been pushed to npm. It was a mistake I made.

The patch you submitted can't be merged as is. Pointing to `lib` seems to work but it actually doesn't: We saw that es6 modules need a build step with Babel and be transpiled back to es5 to be supported properly hence the nonexistent dist folder which should exist with the npm releases. 

As for the middleware, you're 100% right. It plain didn't work. Apologies. 

We need to publish a prebuilt, functional release on npm which we will do shortly.

**Comment by agonbina** [comment]
The babel build step will be spitting es5 modules to `lib`(not to be confused with `src` where the es6 modules live) and this will work as it stands the next time you publish a new version to npm(and `npm prepublish` runs so you get the `lib` source included in the npm distribution. 

You can also look into adding a `jsnext:main` property to package.json to make it compatible with other build tools like Webpack(which I'm using), Browserify or Rollup([jsnext](https://github.com/rollup/rollup/wiki/jsnext:main)]

**Comment by unity** [comment]
Just re-read your comment. You actually are right about package.json.
This is what happens when you reply from an iPhone.

I Will review and merge.

**Comment by agonbina** [comment]
:+1:

**Comment by agonbina** [comment]
So after experimenting with the library for a while, one thing that I noticed was that the current user middleware does not handle the case when the user is not authenticated. I understand that you can add another middleware which would check if `req.hull.userId` is not set and then do the error handling there.

However to me it seems that there should be a default in the middleware itself, because if I add a middleware that checks if the user is authenticated, and the user is not authenticated, I expect the middleware stack to stop executing exactly at that point.

I'm suggesting this implementation here, if you think it makes sense, let me know I can add this to the PR.

```js
export default function(config = {}, req, res, next) {
  const cookies = req.cookies || {};
  const { platformId } = config;
  const cookieName = `hull_${platformId}`;
  const notAuthenticated = new Error('User is not authenticated.');
  if (!(cookieName in cookies)) { 
    return next(notAuthenticated); 
  }

  const signedUser = parseSignedCookie(cookies[cookieName]);
  const userId = signedUser['Hull-User-Id'];
  const userSig = signedUser['Hull-User-Sig'];

  if (signedUser) {
    const valid = crypto.currentUserId(config, userId, userSig);
    if (!!valid) {
      req.hull = { userId }
      return next()
    }
  }
  // If we are not able to parse and unsign the cookie, the user is not authenticated correctly
  return next(notAuthenticated);
}
```

p.s. I've tested the code above and it works fine

**Comment by unity** [comment]
Thanks @agon, that's amazing! We'll look into it really soon!


Sent from a small keyboard with no real keyboard.

Romain Dardour. Co-founder, @hull
Romain@hull.io — www.hull.io

**Comment by unity** [comment]
We'll merge your PR, it's great!

OTOH I don't think your proposed implementation of throwing an error if the user isn't logged should be the default behaviour. Not having a User isn't an error per se.
I think the middleware should be seen as an enrichment layer to the response object; Just as a cookie middleware shouldn't throw if there's no cookie, the Identity middleware shouldn't throw if there's no user. 

Any thoughts?

**Comment by agonbina** [comment]
Hi Romain,

Actually my suggestion was not to throw an error that would crash the Node process(if not caught), but pass a meaningful "error message" that would let the request

Most authentication SDKs treat middlewares as something you can either pass through or be stopped at, for example here is the [loginRequired](http://docs.stormpath.com/nodejs/express/latest/authentication.html#cookie-authentication) middleware from the express.js SDK of stormpath.com(an identity as a service API)

The fairly popular passport.js library does the same thing in their `Authenticate` middleware: http://passportjs.org/docs/authenticate

But it is up to you to keep the middleware the way it is :+1: my personal preference is that, if the user is not authenticated, the [default error handler](http://expressjs.com/en/guide/error-handling.html) in my Express.js server configuration will know how to handle it and I will use this [fork](https://github.com/agonbina/hull-node/commit/77dd3ee6aa01c17a2f687f60ce93f81f55afbd2f) for now :)

**Pull request merged**
